config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users do
      get :export, on: :collection
    end

    resources :task_submissions

    resources :reviews do
      get :export, on: :collection
    end

    root to: 'users#index'
  end
  # FIXME: restrict to admin only
  # https://github.com/mperham/sidekiq/wiki/Monitoring
  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'

  root to: 'home#show'

  get :terms, to: "home#terms"
  get :stats, to: "home#stats"

  get :logout, to: "users#logout"
  post 'first_step', to: "users#first_step"
  get 'first_step', to: redirect("/")

  resource :students, only: [:new, :show] do
    get :login_with_token
    resource :student_application_form, only: [:new, :show, :create] do
    end
    resource :task, only: [:new, :create, :edit, :update] do
      get 'javascript'
      get 'java'
      get 'ruby'
      get 'cpp'
      get 'python'
      get 'c'
    end
    resource :student_evaluation, only: [:show]
  end

  namespace :review do
    get '/', to: "dashboard#index"
    get :student, to: "dashboard#student"
    get :save_review, to: "dashboard#student"
    post :save_review, to: "dashboard#save_review"
    post :save_quick_review, to: "dashboard#save_quick_review"
    get :begin_review, to: "dashboard#begin_review"
    get :download_qualified_students, to: "dashboard#download_qualified_students"
    get :download_marginal_students, to: "dashboard#download_marginal_students"
    get :download_unqualified_students, to: "dashboard#download_unqualified_students"
    get :download_all_students_csv, to: "dashboard#download_all_students_csv"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :fetch_active_student
  before_action :show_if_active_student, except: %w[terms stats]

  def show
  end

  def terms
    redirect_to "https://drive.google.com/file/d/1qQ0VugHXozra2qc_95wXNLcFC4rmIJEp/view"
  end

  def stats
  end
end

app/views/home/_review_stats.html.erb
<div class="mt-10">
  <div class="font-bold text-lg text-primary-800"> <%= title %></div>
  <table class="table-auto mx-auto w-full text-primary-700">
    <thead class="border mt-2">
    <tr>
      <th class="px-4 py-2 border-r">Score</th>
      <th class="px-4 py-2">Students</th>
    </tr>
    </thead>
    <tbody>
    <% grades.each do |grade| %>
      <% unless grade[0].blank? %>
        <tr>
          <td class="border px-4 py-2"><%= grade[0].blank? ? "Yet to update" : grade[0] %></td>
          <td class="border px-4 py-2"><%= grade[1] %></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/home/show.html.erb
<main class="max-w-2xl border border-gray-700 shadow-lg bg-gray-800 p-4 md:p-6 rounded-lg mt-4">
  <%= form_tag(first_step_path, :multipart => true) do %>
    <div>
      <label for="email">
        <p class="font-montserrat text-primary-700 tracking-wide text-base md:text-lg">Before we begin, please tell us your email address!</p>
        <%= email_field_tag 'email', nil, required: true, placeholder: "abc@xyz.com", class: 'mt-2 shadow-sm bg-gray-900 border-gray-600 font-spacemono text-white focus:ring-1 focus:ring-primary-500 focus:border-primary-500 focus:ring-opacity-50 block w-full sm:text-sm rounded' %>
      </label>
    </div>
    <button type="submit" class="mt-4 flex items-center justify-center w-full md:w-auto text-center text-base font-medium px-6 py-3 bg-gradient-to-b from-primary-400 to-primary-700 text-gray-900 border border-primary-300 font-montserrat rounded shadow-lg focus:ring-2 focus:ring-primary-200 hover:shadow-xl focus:from-primary-500 focus:to-primary-900 hover:from-primary-600 hover:to-primary-900 transition duration-250 ease-in-out">
      <span>Continue</span>
      <span class="pl-3">
        <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd" />
        </svg>
      </span>
    </button>
  <% end %>
</main>

app/views/home/stats.html.erb
<% students = User.kept %>
<% @stats_page = true %>
<%
  states = User.kept.group(:state).count.sort_by { |e| e[1] }.reverse
  sources = User.kept.group(:source).count.sort_by { |e| e[1] }.reverse
  email_unverified = students.where(status: User::EMAIL_UNVERIFIED).count
  total_application = students.count
  email_verified = students.where(status: User::EMAIL_VERIFIED).count
  application_submitted = students.where(status: User::APPLICATION_FORM_SUBMITTED).count
  task_revealed = students.where(status: User::TASK_REVEALED).count
  task_submitted = students.where(status: User::TASK_SUBMITTED).count
  task_reviewed = students.where(status: User::TASK_REVIEWED).count
  holistic_evaluation = Review.group(:holistic_evaluation).count
  tests_passing = Review.group(:tests_passing).count
  clean_code = Review.group(:clean_code).count
  program_design = Review.group(:program_design).count
  language_selection = Review.group(:language_selection).count
  portfolio_quality = Review.group(:portfolio_quality).count
%>
<div>
  <table class="table-auto mx-auto w-full text-primary-700">
    <tbody>
    <tr>
      <td class="border px-4 py-2">Total Applications</td>
      <td class="border px-4 py-2"><%= total_application %></td>
    </tr>
    <tr>
      <td class="border px-4 py-2">Email UnVerified</td>
      <td class="border px-4 py-2"><%= email_unverified %></td>
    </tr>
    <tr>
      <td class="border px-4 py-2">Email Verified</td>
      <td class="border px-4 py-2"><%= total_application - email_unverified %></td>
    </tr>
    <tr>
      <td class="border px-4 py-2">Application form Submitted</td>
      <td class="border px-4 py-2"><%= application_submitted + task_revealed + task_submitted + task_reviewed %></td>
    </tr>
    <tr>
      <td class="border px-4 py-2">Task Revealed</td>
      <td class="border px-4 py-2"><%= task_revealed + task_submitted + task_reviewed %></td>
    </tr>
    <tr>
      <td class="border px-4 py-2">Task Submitted</td>
      <td class="border px-4 py-2"><%= task_submitted + task_reviewed %></td>
    </tr>
    <tr>
      <td class="border px-4 py-2">Task Reviewed</td>
      <td class="border px-4 py-2"><%= task_reviewed %></td>
    </tr>
    </tbody>
  </table>
</div>

<div>
  <div class="mt-10">
    <div class="font-bold text-lg text-primary-800"> States -
      <%= states.count - 1 %></div>
    <table class="table-auto mx-auto w-full text-primary-700">
      <thead class="border mt-2">
      <tr>
        <th class="px-4 py-2 border-r">State</th>
        <th class="px-4 py-2">Students</th>
      </tr>
      </thead>
      <tbody>
      <% states.each do |state| %>
        <% unless state[0].blank? %>
          <tr>
            <td class="border px-4 py-2"><%= state[0].blank? ? "Yet to update" : state[0] %></td>
            <td class="border px-4 py-2"><%= state[1] %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="mt-10">
    <div class="font-bold text-lg text-primary-800"> Source</div>
    <table class="table-auto mx-auto w-full text-primary-700">
      <thead class="border mt-2">
      <tr>
        <th class="px-4 py-2 border-r">Medium</th>
        <th class="px-4 py-2">Students</th>
      </tr>
      </thead>
      <tbody>
      <% sources.each do |source| %>
        <% unless source[0].blank? %>
          <tr>
            <td class="border px-4 py-2"><%= source[0].blank? ? "Yet to update" : source[0] %></td>
            <td class="border px-4 py-2"><%= source[1] %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="mt-10">
    <h4 class="text-gray-200">Review Stats</h4>
  </div>
  <%= render 'review_stats', title: 'Holistic Evaluation', grades: holistic_evaluation %>
  <%= render 'review_stats', title: 'Tests Passing', grades: tests_passing %>
  <%= render 'review_stats', title: 'Clean Code', grades: clean_code %>
  <%= render 'review_stats', title: 'Program Design', grades: program_design %>
  <%= render 'review_stats', title: 'Language Selection', grades: language_selection %>
  <%= render 'review_stats', title: 'Portfolio Quality', grades: portfolio_quality %>

</div>