config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users do
      get :export, on: :collection
    end

    resources :task_submissions

    resources :reviews do
      get :export, on: :collection
    end

    root to: 'users#index'
  end
  # FIXME: restrict to admin only
  # https://github.com/mperham/sidekiq/wiki/Monitoring
  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'

  root to: 'home#show'

  get :terms, to: "home#terms"
  get :stats, to: "home#stats"

  get :logout, to: "users#logout"
  post 'first_step', to: "users#first_step"
  get 'first_step', to: redirect("/")

  resource :students, only: [:new, :show] do
    get :login_with_token
    resource :student_application_form, only: [:new, :show, :create] do
    end
    resource :task, only: [:new, :create, :edit, :update] do
      get 'javascript'
      get 'java'
      get 'ruby'
      get 'cpp'
      get 'python'
      get 'c'
    end
    resource :student_evaluation, only: [:show]
  end

  namespace :review do
    get '/', to: "dashboard#index"
    get :student, to: "dashboard#student"
    get :save_review, to: "dashboard#student"
    post :save_review, to: "dashboard#save_review"
    post :save_quick_review, to: "dashboard#save_quick_review"
    get :begin_review, to: "dashboard#begin_review"
    get :download_qualified_students, to: "dashboard#download_qualified_students"
    get :download_marginal_students, to: "dashboard#download_marginal_students"
    get :download_unqualified_students, to: "dashboard#download_unqualified_students"
    get :download_all_students_csv, to: "dashboard#download_all_students_csv"
  end
end

app/controllers/admin/reviews_controller.rb
module Admin
  class ReviewsController < Admin::ApplicationController
    include AdministrateExportable::Exporter

    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
    def valid_action?(name, resource = resource_class)
      %w[new edit destroy].exclude?(name.to_s) && super
    end

    def default_sorting_attribute
      :created_at
    end

    def default_sorting_direction
      :desc
    end
  end
end

app/controllers/review/dashboard_controller.rb
class Review::DashboardController < ReviewController
  def index
    @filter = UserFilter.new(params[:status])
    students = @filter.filtered
    @filtered_count = students.count
    @students = students.page(params[:page]).per(50)
  end

  def student
    @student = User.find(params[:id])
    @review = @student.review || @student.build_review
  end

  def begin_review
    next_student = User.next_student_for_review
    if next_student.count == 1
      student = next_student.first
      redirect_to review_student_path(id: student.id)
    else
      flash[:info] = "No more students left to review!"
      redirect_to review_path
    end
  end

  def save_review
    r = params[:review]
    @student = User.find(params[:id])
    @review = @student.review || @student.build_review

    @review.tests_passing = r[:tests_passing]
    @review.clean_code = r[:clean_code]
    @review.program_design = r[:program_design]
    @review.language_selection = r[:language_selection]
    @review.portfolio_quality = r[:portfolio_quality]
    @review.holistic_evaluation = r[:holistic_evaluation]
    @review.private_notes = r[:private_notes]
    if @review.save
      @student.mark_task_reviewed!
      flash.clear
      redirect_to review_begin_review_path
    else
      flash[:error] = @review.errors.map { |attr, msg| "#{attr} #{msg}" }
      render :'review/dashboard/student'
    end
  end

  def save_quick_review
    @student = User.find(params[:id])
    @review = @student.review || @student.build_review

    if params[:unrelated_submission] || params[:empty_submission] || params[:plagiarized_dp]
      @review.tests_passing = 0
      @review.clean_code = 0
      @review.program_design = 0
      @review.language_selection = 0
      @review.portfolio_quality = 0
      @review.holistic_evaluation = 0
      if params[:unrelated_submission]
        @review.private_notes = "Unrelated submission."
      elsif params[:empty_submission]
        @review.private_notes = "Empty submission."
      elsif params[:plagiarized_dp]
        @review.private_notes = "Dhruv Panchal."
      end
    elsif params[:unqualified]
      @review.tests_passing = 0
      @review.clean_code = 0
      @review.program_design = 0
      @review.language_selection = 0
      @review.portfolio_quality = 0
      @review.holistic_evaluation = 0
      @review.private_notes = "Quick review - Unqualified."
    elsif params[:at_par]
      language = @student.task_submissions.last.main_program_extname
      if %w[py js rb].include?(language)
        @review.language_selection = 1
      else
        @review.language_selection = 0
      end
      @review.tests_passing = 0
      @review.clean_code = 1
      @review.program_design = 1
      @review.portfolio_quality = 0
      @review.holistic_evaluation = 1
      @review.private_notes = "Quick review - At Par."
    else
      flash[:error] = "Invalid quick review type"
      redirect_to review_begin_review_path
      return
    end

    if @review.save
      @student.mark_task_reviewed!
      flash.clear
      flash[:info] = "Marked previous review as #{@review.private_notes}"
      redirect_to review_begin_review_path
    else
      flash[:error] = @review.errors.map { |attr, msg| "#{attr} #{msg}" }
      render :'review/dashboard/student'
    end
  end

  def download_qualified_students
    download(User.qualified_students, 'qualified')
  end

  def download_marginal_students
    download(User.marginal_students, 'marginal')
  end

  def download_unqualified_students
    download(User.unqualified_students, 'unqualified')
  end

  def download_all_students_csv
    filename = StudentsDataExport.new().begin_export!
    send_file(filename)
  end

  private

  def download(scope, filename_prefix)
    send_data SubmittedStudentsDataExport.new(scope).to_csv,
      filename: "#{filename_prefix}-#{Date.today.to_s(:short)}.csv"
  end
end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
  before_action :fetch_active_student
  before_action :ensure_active_student
  before_action :ensure_admin

  private

  def ensure_admin
    unless @student.is_admin?
      flash[:error] = "You have to be an admin to review"
      redirect_to root_path
      return
    end
    @is_admin_page = true
    @admin = @student
    @student = nil
  end
end

app/views/review/dashboard/_language_selection.html.erb
<div class="mb-4">
  <p class="text-lg font-bold"><%= caption %></p>

  <div class="radio-toolbar">
    <input type="radio"
           id="<%= field %>_atpar"
           name="review[<%= field %>]"
           value="0"
           <%= review.attributes[field] == 0 ? "checked" : "" %>
    >
    <label for="<%= field %>_atpar">At par</label>

    <input type="radio"
           id="<%= field %>_good"
           name="review[<%= field %>]"
           value="1"
           <%= review.attributes[field] == 1 ? "checked" : "" %>
    >
    <label for="<%= field %>_good">Good</label>
  </div>
</div>

app/views/review/dashboard/_review_metric.html.erb
<%
  unq_caption ||= "Unqualified"
  atpar_caption ||= "At par"
  good_caption ||= "Good"
%>

<div class="mb-4">
  <p class="text-lg font-bold"><%= caption %></p>

  <div class="radio-toolbar">
    <input type="radio"
           id="<%= field %>_unq"
           name="review[<%= field %>]"
           value="0"
           <%= review.attributes[field] == 0 ? "checked" : "" %>
    >
    <label for="<%= field %>_unq"><%= unq_caption %></label>

    <input type="radio"
           id="<%= field %>_par"
           name="review[<%= field %>]"
           value="1"
           <%= review.attributes[field] == 1 ? "checked" : "" %>
    >
    <label for="<%= field %>_par"><%= atpar_caption %></label>

    <input type="radio"
           id="<%= field %>_good"
           name="review[<%= field %>]"
           value="2"
           <%= review.attributes[field] == 2 ? "checked" : "" %>
    >
    <label for="<%= field %>_good"><%= good_caption %></label>
  </div>
</div>

app/views/review/dashboard/_submission_review.html.erb
<div class="mb-48">

<pre class="ReviewPage-codeSubmission"><code>
<%== student.task_submissions.last.main_program_text %>
</code></pre>

  <div class="flex">
    <%= button_to "Unqualified", review_save_quick_review_path(id: @student.id, unqualified: true), class: "mr-8 bg-red-800 text-white" %>
    <%= button_to "At par", review_save_quick_review_path(id: @student.id, at_par: true), class: "mr-8 bg-red-800 text-white" %>
    <%= button_to "Plagiarized (DP)", review_save_quick_review_path(id: @student.id, plagiarized_dp: true), class: "mr-8 bg-red-800 text-white" %>
  </div>
</div>

<div class="flex items-center">
  <div class="mr-32">
    <div class="max-w-xs my-4 bg-white">
      <%= link_to "Automated tests", "https://github.com/nseadlc-2020/#{student.id}/actions?query=workflow%3A%22Node.js+Test+Runner%22", class: "block py-4 px-0 text-center" %>
    </div>

    <div class="max-w-xs mt-4 bg-white mr-8">
      <%= link_to "Download Code", url_for(student.task_submissions.last.uploaded_file), class: "block text-center p-4" %>
    </div>
  </div>
  <div class="">
    <p class="my-4">
      <%= button_to "Mark as Unrelated Submission", review_save_quick_review_path(id: @student.id, unrelated_submission: true), class: "mr-8 bg-red-800 text-white" %>
    </p>
    <p class="mt-4">
      <%= button_to "Mark as Empty Submission", review_save_quick_review_path(id: @student.id, empty_submission: true), class: "mr-8 bg-red-800 text-white" %>
    </p>
  </div>
</div>

<%= form_tag(review_save_review_path(id: @student.id), class: "pb-16") do %>
  <div class="grid gap-4 grid-cols-2 mt-8">
    <%= render partial: "review_metric", locals: {
      review: review,
      caption: "Tests passing",
      field: "tests_passing",
      unq_caption: "Missing tests/0 passing",
      atpar_caption: "Some passing",
      good_caption: "All passing"
    } %>

    <%= render partial: "review_metric", locals: {
      review: review,
      caption: "Code cleanliness",
      field: "clean_code",
    } %>

    <%= render partial: "review_metric", locals: {
      review: review,
      caption: "Program design",
      field: "program_design",
    } %>

    <%= render partial: "language_selection", locals: {
      review: review,
      caption: "Language selection",
      field: "language_selection",
    } %>
  </div>

  <div class="grid gap-4 grid-cols-2 mt-8">
    <div class="mb-4 ReviewPage-text">
      <p class="text-gray-200 mb-1 text-sm">Portfolio</p>
      <%== simple_format(student.portfolio).gsub(URI.regexp, '<a href="\0">\0</a>').html_safe %>
    </div>

    <div class="mb-4 ReviewPage-text">
      <p class="text-gray-200 mb-1 text-sm">What excites you about programming?</p>
      <%== simple_format(student.anything_else).gsub(URI.regexp, '<a href="\0">\0</a>').html_safe %>
    </div>

    <%= render partial: "review_metric", locals: {
      review: review,
      caption: "Portfolio quality",
      field: "portfolio_quality",
      unq_caption: "Not enough data",
      atpar_caption: "At par",
      good_caption: "Good"
    } %>

    <%= render partial: "review_metric", locals: {
      review: review,
      caption: "Holistic evaluation",
      field: "holistic_evaluation",
      good_caption: "Qualified"
    } %>

    <div class="mb-4">
      <p>Private notes:</p>
      <%= text_area "review", "private_notes", class: "mt-2 shadow-sm bg-gray-900 border-gray-600 font-spacemono text-white focus:ring-1 focus:ring-primary-500 focus:border-primary-500 focus:ring-opacity-50 block w-full sm:text-sm rounded h-16" %>
    </div>
  </div>

  <button type="submit" class="mt-4 flex items-center justify-center w-full md:w-auto text-center text-base font-medium px-6 py-3 bg-gradient-to-b from-primary-400 to-primary-700 text-gray-900 border border-primary-300 font-montserrat rounded shadow-lg focus:ring-2 focus:ring-primary-200 hover:shadow-xl focus:from-primary-500 focus:to-primary-900 hover:from-primary-600 hover:to-primary-900 transition duration-250 ease-in-out">
    <span>Save Review &amp; Continue</span>
  </button>
<% end %>

app/views/review/dashboard/index.html.erb
<div class="flex justify-between text-white border border-gray-600">
  <div>
    <%= link_to review_path(status: nil), class: "p-4 block text-white" do %>
      All (<%= User.kept.count %>)
    <% end %>
  </div>
  <div>
    <%= link_to review_path(status: User::APPLICATION_FORM_SUBMITTED), class: "p-4 block" do %>
      Form Submitted (<%= User.kept.where(status: User::APPLICATION_FORM_SUBMITTED).count %>)
    <% end %>
  </div>
  <div>
    <%= link_to review_path(status: User::TASK_SUBMITTED), class: "p-4 block" do %>
      Pending Review (<%= User.kept.where(status: User::TASK_SUBMITTED).count %>)
    <% end %>
  </div>
  <div>
    <%= link_to review_path(status: User::TASK_REVIEWED), class: "p-4 block" do %>
      Reviewed (<%= User.kept.where(status: User::TASK_REVIEWED).count %>)
    <% end %>
  </div>
  <div>
    <%= link_to review_path(status: "qualified"), class: "p-4 block" do %>
      Qualified (<%= User.qualified_students.count %>)
    <% end %>
  </div>
</div>

<main class="ReviewPage">
  <h2 class="mt-8 text-white text-base">
    <p class="text-xl mb-4"><%= @filter.to_string %></p>
    <%= page_entries_info @students, entry_name: 'student' %>
  </h2>
  <div class="mt-8 bg-gray-700 text-white p-2">
    <div class="text-xl">
      <%= paginate @students %>
    </div>
  </div>
  <table class="review-table bg-white">
    <thead>
    <tr>
      <th></th>
      <th>name</th>
      <th>code submitted at</th>
      <th>last updated at</th>
      <% unless @filter.active? %>
        <th>status</th>
      <% end %>
      <th>email</th>
    </tr>
    </thead>
    <tbody>
    <% @students.each do |s| %>
      <tr>
        <td>
          <%= link_to "Review", review_student_path(id: s.id), class: "block text-sm", style: "padding: 16px;" %>
        </td>
        <td>
          <p class="text-gray-800">
            <%= s.display_name %>
          </p>
        </td>

        <td>
          <p class="text-gray-800">
            <% if s.task_submitted_at %>
              <%= time_ago_in_words(s.task_submitted_at) %> ago
            <% end %>
          </p>
        </td>

        <td>
          <p class="text-gray-800">
            <%= time_ago_in_words(s.updated_at) %> ago
          </p>
        </td>

        <% unless @filter.active? %>
          <td>
            <p class="text-gray-800">
              <%= s.status %>
            </p>
          </td>
        <% end %>
        <td class="text-gray-800">
          <p class="text-gray-800">
            <%= s.email %>
          </p>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <div class="mb-8 bg-gray-700 text-white p-2">
    <div class="text-xl">
      <%= paginate @students %>
    </div>
  </div>
</main>

app/views/review/dashboard/student.html.erb
<main class="ReviewPage">
  <% if @student.status == User::TASK_SUBMITTED || @student.status == User::TASK_REVIEWED %>
    <p class="mt-4">
      <%= User.kept.where(status: User::TASK_SUBMITTED).count %>
      submissions left to be reviewed.
    </p>
  <% end %>

  <div class="text-white mt-12 text-sm">
    <div class="font-bold mb-4">
      <p class="mb-2 text-2xl"><%= @student.full_name %></p>
    </div>

    <div class="mb-4 ReviewPage-text hidden">
      <a href="mailto:<%= @student.email %>" class="block mb-4 font-normal"><%= @student.email %></a>
      <p class="text-gray-200 mb-1 text-sm">Course, College</p>
      <%= @student.semester.to_i.ordinalize %> semester, <%= @student.course %>, <%= @student.college %>
    </div>
  </div>

  <p class="mb-4">
    <%= @student.status.upcase %>
  </p>

  <div class="max-w-xs my-8 bg-white mr-8">
    <%= link_to "View in Admin interface", "/admin/users/#{@student.id}", class: "block text-center p-4" %>
  </div>

  <% if @student.status == User::TASK_SUBMITTED || @student.status == User::TASK_REVIEWED %>
    <%= render partial: 'submission_review', locals: { student: @student, review: @review } %>
  <% end %>
</main>