config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users do
      get :export, on: :collection
    end

    resources :task_submissions

    resources :reviews do
      get :export, on: :collection
    end

    root to: 'users#index'
  end
  # FIXME: restrict to admin only
  # https://github.com/mperham/sidekiq/wiki/Monitoring
  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'

  root to: 'home#show'

  get :terms, to: "home#terms"
  get :stats, to: "home#stats"

  get :logout, to: "users#logout"
  post 'first_step', to: "users#first_step"
  get 'first_step', to: redirect("/")

  resource :students, only: [:new, :show] do
    get :login_with_token
    resource :student_application_form, only: [:new, :show, :create] do
    end
    resource :task, only: [:new, :create, :edit, :update] do
      get 'javascript'
      get 'java'
      get 'ruby'
      get 'cpp'
      get 'python'
      get 'c'
    end
    resource :student_evaluation, only: [:show]
  end

  namespace :review do
    get '/', to: "dashboard#index"
    get :student, to: "dashboard#student"
    get :save_review, to: "dashboard#student"
    post :save_review, to: "dashboard#save_review"
    post :save_quick_review, to: "dashboard#save_quick_review"
    get :begin_review, to: "dashboard#begin_review"
    get :download_qualified_students, to: "dashboard#download_qualified_students"
    get :download_marginal_students, to: "dashboard#download_marginal_students"
    get :download_unqualified_students, to: "dashboard#download_unqualified_students"
    get :download_all_students_csv, to: "dashboard#download_all_students_csv"
  end
end

app/controllers/student_application_forms_controller.rb
class StudentApplicationFormsController < ApplicationController
  before_action :fetch_active_student
  before_action :ensure_active_student
  before_action :allow_only_email_verified_students

  def show
    # GET /students/student_application_form
    # Happens when page is refreshed after a failed submit (POST create)
    redirect_to new_students_student_application_form_path
  end

  def new
    @form = StudentApplicationForm.new(
      {
        email: @student.email,
        first_name: @student.first_name,
        full_name: @student.full_name,
        dob: @student.dob,
        college: @student.college,
        portfolio: @student.portfolio,
        anything_else: @student.anything_else,
        source: @student.source,
        state: @student.state,
        phone_number: @student.phone_number,
        semester: @student.semester,
        course: @student.course,
        terms_agreed: @student.terms_agreed_at.present?
      })
  end

  def create
    p = params[:form]
    attrs = {
      email: @student.email,
      first_name: p[:first_name],
      full_name: p[:full_name],
      dob: p[:dob],
      college: p[:college],
      portfolio: p[:portfolio],
      anything_else: p[:anything_else],
      source: p[:source],
      state: p[:state],
      phone_number: p[:phone_number],
      semester: p[:semester],
      course: p[:course],
      terms_agreed: p[:terms_agreed]
    }

    @form = StudentApplicationForm.new(attrs)
    @form.validate

    if @form.valid?
      attrs.delete :terms_agreed
      attrs[:terms_agreed_at] = DateTime.now

      @student.submit_application_form!(attrs)
      flash[:success] = "Thanks, your application form is now saved. Please continue to the next step."
      redirect_to students_path
    else
      flash[:error] = @form.errors.map { |attr, msg| msg }
      render :new
    end
  end

  private

  def allow_only_email_verified_students
    # if application already filled, can't update. can only do
    # the subsequent steps
    unless @student.status_email_verified?
      flash[:info] = "Application is already filled"
      redirect_to root_path
    end
  end

end

app/views/student_application_forms/new.html.erb
<h1 class="text-white text-lg md:text-xl pt-2 font-medium">1. Fill in application form</h1>
<main class="max-w-2xl border border-gray-700 shadow-lg bg-gray-800 p-4 md:p-6 rounded-lg mt-4">
  <%= form_tag(students_student_application_form_path) do %>
    <div>
      <%= label "form", "email" do %>
        <p class="font-montserrat text-primary-700 tracking-wide text-base md:text-lg">
          Your email address:
        </p>
        <%= email_field "form", "email", readonly: true, class: "cursor-not-allowed mt-2 shadow-sm bg-gray-900 border-transparent font-spacemono text-gray-200 focus:ring-0 focus:border-transparent block w-full sm:text-sm rounded disbaled" %>
      <% end %>
    </div>

    <div class="mt-6 md:mt-10">
      <%= label "form", "first_name" do %>
        <p class="font-montserrat text-primary-700 tracking-wide text-base md:text-lg">
          What is your first name?
          <small class="font-spacemono text-sm text-gray-100 block">
            We will use this name to address you.
          </small>
        </p>
        <%= text_field "form", "first_name", autofocus: true, class: "mt-2 shadow-sm bg-gray-900 border-gray-600 font-spacemono text-white focus:ring-1 focus:ring-primary-500 focus:border-primary-500 focus:ring-opacity-50 block w-full sm:text-sm rounded" %>
      <% end %>
    </div>

    <div class="mt-6 md:mt-10">
      <%= label "form", "full_name" do %>
        <p class="font-montserrat text-primary-700 tracking-wide text-base md:text-lg">
          What is your full name?
          <small class="font-spacemono text-sm text-gray-100 block">
            As it appears in your official records.
          </small>
        </p>
        <%= text_field "form", "full_name", class: "mt-2 shadow-sm bg-gray-900 border-gray-600 font-spacemono text-white focus:ring-1 focus:ring-primary-500 focus:border-primary-500 focus:ring-opacity-50 block w-full sm:text-sm rounded" %>
      <% end %>
    </div>

    <div class="mt-6 md:mt-10">
      <%= label "form", "phone_number" do %>
        <p class="font-montserrat text-primary-700 tracking-wide text-base md:text-lg">
          What is your valid mobile number?
        </p>
        <%= phone_field "form", "phone_number", class: "mt-2 shadow-sm bg-gray-900 border-gray-600 font-spacemono text-white focus:ring-1 focus:ring-primary-500 focus:border-primary-500 focus:ring-opacity-50 block w-full sm:text-sm rounded" %>
      <% end %>
    </div>

    <div class="mt-6 md:mt-10">
      <%= label "form", "dob" do %>
        <p class="font-montserrat text-primary-700 tracking-wide text-base md:text-lg">
          What is your date of birth?
          <small class="font-spacemono text-sm text-gray-100 block">
            You have to be between 18 and 25 years to participate in this program.
          </small>
        </p>
        <%= date_field "form", "dob", min: "1995-01-01", max: "2003-01-01", class: "mt-2 shadow-sm bg-gray-900 border-gray-600 font-spacemono text-white focus:ring-1 focus:ring-primary-500 focus:border-primary-500 focus:ring-opacity-50 block w-full sm:text-sm rounded" %>
      <% end %>
    </div>

    <div class="mt-6 md:mt-10">
      <%= label "form", "course" do %>
        <p class="font-montserrat text-primary-700 tracking-wide text-base md:text-lg">
          Course/Program that you are currently enrolled in at your University/College?
          <small class="font-spacemono text-sm text-gray-100 block">
            For eg: B.Tech (Electronics and Communication Engineering)
          </small>
        </p>
        <%= text_field "form", "course", class: "mt-2 shadow-sm bg-gray-900 border-gray-600 font-spacemono text-white focus:ring-1 focus:ring-primary-500 focus:border-primary-500 focus:ring-opacity-50 block w-full sm:text-sm rounded" %>
      <% end %>
    </div>


    <div class="mt-6 md:mt-10">
      <%= label "form", "semester" do %>
        <p class="font-montserrat text-primary-700 tracking-wide text-base md:text-lg">Which semester will you be in Jan-Apr 2021?</p>
        <%= select("form", "semester", User::VALID_SEMESTERS, prompt: 'Please select') %>
      <% end %>
    </div>

    <div class="mt-6 md:mt-10">
      <%= label "form", "college" do %>
        <p class="font-montserrat text-primary-700 tracking-wide text-base md:text-lg">
          Your college and university name, and its location?
          <small class="font-spacemono text-sm text-gray-100 block">
            for eg: IIIT, Hyderabad
          </small>
        </p>
        <%= text_field "form", "college", class: "mt-2 shadow-sm bg-gray-900 border-gray-600 font-spacemono text-white focus:ring-1 focus:ring-primary-500 focus:border-primary-500 focus:ring-opacity-50 block w-full sm:text-sm rounded" %>
      <% end %>
    </div>

    <div class="mt-6 md:mt-10">
      <%= label "form", "state" do %>
        <p class="font-montserrat text-primary-700 tracking-wide text-base md:text-lg">In which state is your University/College located at?</p>
        <%= select("form", "state", User::VALID_STATES, prompt: 'Please select') %>
      <% end %>
    </div>

    <div class="mt-6 md:mt-10">
      <%= label "form", "portfolio" do %>
        <p class="font-montserrat text-primary-700 tracking-wide text-base md:text-lg">
          Links to anything digital you have created?
          <small class="font-spacemono text-sm text-gray-100 block">
            Websites, webapps, simple programs, or just code you wrote
          </small>
        </p>
        <%= text_area "form", "portfolio", class: "mt-2 shadow-sm bg-gray-900 border-gray-600 font-spacemono text-white focus:ring-1 focus:ring-primary-500 focus:border-primary-500 focus:ring-opacity-50 block w-full sm:text-sm rounded" %>
      <% end %>
    </div>

    <div class="mt-6 md:mt-10">
      <%= label "form", "anything_else" do %>
        <p class="font-montserrat text-primary-700 tracking-wide text-base md:text-lg">
          Anything else you might want to add?
          <small class="font-spacemono text-sm text-gray-100 block">
            and do tell us about what you enjoy about programming!
          </small>
        </p>
        <%= text_area "form", "anything_else", class: "mt-2 shadow-sm bg-gray-900 border-gray-600 font-spacemono text-white focus:ring-1 focus:ring-primary-500 focus:border-primary-500 focus:ring-opacity-50 block w-full sm:text-sm rounded" %>
      <% end %>
    </div>

    <div class="mt-6 md:mt-10">
      <%= label "form", "source" do %>
        <p class="font-montserrat text-primary-700 tracking-wide text-base md:text-lg">How did you get to know about this programme?</p>
        <%= select("form", "source", User::VALID_SOURCE, prompt: 'Please select') %>
      <% end %>
    </div>

    <div class="mt-6 md:mt-10">
      <%= label "form", "terms_agreed" do %>
        <p class="font-montserrat text-primary-700 tracking-wide text-base md:text-lg">
          Do you agree to the Terms for Participation in the program?
        </p>
        <div class="flex items-start md:items-center mt-4">
          <%= check_box("form", "terms_agreed", class: "mr-4 block bg-gray-900 rounded focus:ring-1 focus:ring-primary-500") %>
          <span class="block text-sm md:text-base text-white">
            I have read and I agree to the <%= link_to "Terms for Participation", terms_path, class:"border-b border-primary-500 text-primary-200 hover:bg-primary-200 hover:text-gray-900" %>
          </span>
        </div>
      <% end %>
    </div>
    <p class="text-white mt-6 text-base">
      Do read the form once more and make sure everything is written as well as you can. Submit when you're
      ready!
    </p>
    <p>
      <button type="submit" class="mt-4 flex items-center justify-center w-full md:w-auto text-center text-base font-medium px-6 py-3 bg-gradient-to-b from-primary-400 to-primary-700 text-gray-900 border border-primary-300 font-montserrat rounded shadow-lg focus:ring-2 focus:ring-primary-200 hover:shadow-xl focus:from-primary-500 focus:to-primary-900 hover:from-primary-600 hover:to-primary-900 transition duration-250 ease-in-out">
        <span>Submit &amp; Continue</span>
        <span class="pl-3">
        <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd" />
        </svg>
      </span>
      </button>
    </p>
  <% end %>
</main>