config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users do
      get :export, on: :collection
    end

    resources :task_submissions

    resources :reviews do
      get :export, on: :collection
    end

    root to: 'users#index'
  end
  # FIXME: restrict to admin only
  # https://github.com/mperham/sidekiq/wiki/Monitoring
  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'

  root to: 'home#show'

  get :terms, to: "home#terms"
  get :stats, to: "home#stats"

  get :logout, to: "users#logout"
  post 'first_step', to: "users#first_step"
  get 'first_step', to: redirect("/")

  resource :students, only: [:new, :show] do
    get :login_with_token
    resource :student_application_form, only: [:new, :show, :create] do
    end
    resource :task, only: [:new, :create, :edit, :update] do
      get 'javascript'
      get 'java'
      get 'ruby'
      get 'cpp'
      get 'python'
      get 'c'
    end
    resource :student_evaluation, only: [:show]
  end

  namespace :review do
    get '/', to: "dashboard#index"
    get :student, to: "dashboard#student"
    get :save_review, to: "dashboard#student"
    post :save_review, to: "dashboard#save_review"
    post :save_quick_review, to: "dashboard#save_quick_review"
    get :begin_review, to: "dashboard#begin_review"
    get :download_qualified_students, to: "dashboard#download_qualified_students"
    get :download_marginal_students, to: "dashboard#download_marginal_students"
    get :download_unqualified_students, to: "dashboard#download_unqualified_students"
    get :download_all_students_csv, to: "dashboard#download_all_students_csv"
  end
end

app/views/layouts/_flash.html.erb
<% if msg %>
  <p class="p-4 mb-4 <%= css %>">
    <% if msg.is_a? String %>
      <%= msg %>
    <% else %>
      <%== msg.join("<br/>") %>
    <% end %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoronaSafe Engineering Fellowship Application</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-VEZME979JN"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'G-VEZME979JN');
  </script>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="bg-gray-800">

<% unless @is_admin_page %>
  <header class="max-w-3xl mx-auto py-4 lg:py-8 px-4 xl:px-0">
    <div class="flex justify-between items-center">
      <%= image_tag('logo-dark.svg', class: 'bock w-36 md:w-44') %>
      <%= image_tag('aicte-logo.png', class: 'block w-20 md:w-24') %>
    </div>
  </header>
<% end %>

<div class='<%= @is_admin_page ? "max-w-5xl mx-auto mt-12" : "max-w-3xl mx-auto py-4 lg:py-8 px-4 xl:px-0" %>'>
  <% if @student %>
    <div class="flex justify-between">
      <% if (current_page?(root_path) || current_page?(students_path)) %>
        <div></div>
      <% else %>
        <p class="text-sm">
          <%= link_to root_path, class: "bg-gray-700 px-2 py-1 rounded text-gray-100 hover:bg-gray-900 hover:shadow-inner hover:text-gray-200" do %>
            <i class="fas fa-home"></i><span class="pl-1">Home</span>
          <% end %>
        </p>
      <% end %>
      <div class="flex md:mb-10 mb-4 space-x-4">
        <p class="hidden md:block text-sm text-gray-500"> <%= @student.more_context_name %> </p>
        <p class="text-sm">
          <%= link_to logout_url, class: "border border-gray-700 px-2 py-1 rounded text-gray-300 hover:bg-gray-900 hover:shadow-inner hover:text-gray-200" do %>
            <i class="fas fa-sign-out-alt"></i><span class="pl-1">Logout</span>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>

  <% if @is_admin_page %>
    <div class="flex mb-4">
      <p class="text-sm mr-8">
        <%= link_to review_begin_review_path, class: "bg-gray-700 px-4 py-2 rounded text-gray-100 hover:bg-gray-900 hover:shadow-inner hover:text-gray-200" do %>
          <i class="fa fa-cubes"></i><span class="pl-1">Begin review</span>
        <% end %>
      </p>
      <p class="text-sm mr-8">
        <%= link_to review_path, class: "bg-gray-700 px-4 py-2 rounded text-gray-100 hover:bg-gray-900 hover:shadow-inner hover:text-gray-200" do %>
          <i class="fa fa-cubes"></i><span class="pl-1">Go to review dashboard</span>
        <% end %>
      </p>
      <p class="text-sm mr-8">
        <%= link_to review_download_qualified_students_path, class: "bg-gray-700 px-4 py-2 rounded text-gray-100 hover:bg-gray-900 hover:shadow-inner hover:text-gray-200" do %>
          <i class="fa fa-download"></i><span class="pl-1">CSV: Qualified students</span>
        <% end %>
      </p>
      <p class="text-sm mr-8">
        <%= link_to review_download_all_students_csv_path, class: "bg-gray-700 px-4 py-2 rounded text-gray-100 hover:bg-gray-900 hover:shadow-inner hover:text-gray-200", 'data-turbolinks' => false do %>
          <i class="fa fa-download"></i><span class="pl-1">CSV: All students</span>
        <% end %>
      </p>
    </div>
  <% else %>
    <h1 class="hidden" style="margin-bottom: 8px; padding-bottom: 0">CoronaSafe Engineering Fellowship</h1>
    <h2 class="text-sm md:text-lg text-gray-300 pb-2 md:pb-8">
      <%= @stats_page ? 'Stats' : 'Application Steps' %>
    </h2>
  <% end %>

  <%= render partial: "layouts/flash", locals: { msg: flash[:info], css: "animation-vibrate font-montserrat bg-blue-100 border border-blue-500 text-blue-900 text-base rounded shadow" } %>
  <%= render partial: "layouts/flash", locals: { msg: flash[:success], css: "animation-vibrate font-montserrat bg-green-100 border border-green-500 text-green-900 text-base rounded shadow" } %>
  <%= render partial: "layouts/flash", locals: { msg: flash[:error], css: "animation-vibrate font-montserrat bg-red-200 border border-red-500 text-red-500 text-base rounded shadow" } %>

  <%= yield %>

  <% unless @is_admin_page %>
    <div class="mt-16 text-sm text-gray-100">
      <div>Please note that it is required that you read and agree to the terms and conditions before applying for the
        program. <%= link_to "Click here to read", terms_path, class: 'border-b border-primary-500 text-white hover:bg-primary-400 hover:text-gray-900' %>
        .
      </div>
      <div class="mt-4">For any questions, email us at
        <a class="border-b border-primary-500 text-white hover:bg-primary-400 hover:text-gray-900" href="mailto:fullstack@pupilfirst.org">fullstack@pupilfirst.org</a>.
      </div>
    </div>
  <% end %>
</div>
</body>
</html>

app/views/layouts/plain_email_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'/>
</head>
<body>
<%= yield %>
</body>
</html>